 GET http://localhost:5000/api/users
# GET http://localhost:5000/api/users/Ed%20Carter
# GET http://localhost:5000/
# POST http://localhost:5000/api/users
# Content-Type: application/json
# {
#   "name":"rocky",
#   "bio":"javascript is fun"
# }
# DELETE http://localhost:5000/api/users/234